package com.example.tennis.controller;

import com.example.tennis.controller.model.CourtDTO;
import com.example.tennis.service.CourtService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@ExtendWith(MockitoExtension.class)
public class CourtControllerTest {

    @Mock
    private CourtService service;

    @InjectMocks
    private CourtController courtController;

    private MockMvc mockMvc;
    private ObjectMapper objectMapper;

    @BeforeEach
    public void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(courtController).build();
        objectMapper = new ObjectMapper();
    }

    private CourtDTO createCourtDTO(String name, String surface) {
        CourtDTO dto = new CourtDTO();
        dto.setGlobalId(UUID.randomUUID());
        dto.setName(name);
        dto.setSurface(surface);
        return dto;
    }

    @Test
    public void testGetAllCourts() throws Exception {
        CourtDTO court1 = createCourtDTO("Court 1", "Clay");
        CourtDTO court2 = createCourtDTO("Court 2", "Grass");
        List<CourtDTO> allCourts = Arrays.asList(court1, court2);

        when(service.getAllCourts()).thenReturn(allCourts);

        mockMvc.perform(get(CourtController.BASE_URL + "/")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].name").value("Court 1"))
                .andExpect(jsonPath("$[1].name").value("Court 2"));

        verify(service, times(1)).getAllCourts();
    }

    @Test
    public void testGetCourtByUuid_Success() throws Exception {
        UUID courtId = UUID.fromString("4930d289-835b-4f60-a326-9bd981389ae6");
        CourtDTO courtDto = createCourtDTO("Court 5", "Gravel");
        courtDto.setGlobalId(courtId);

        when(service.getCourt(any(CourtDTO.class))).thenReturn(courtDto);

        mockMvc.perform(get(CourtController.BASE_URL + "/get")
                        .param("uuid", courtId.toString())
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
                .andExpect(jsonPath("$.globalId").value(courtId.toString()))
                .andExpect(jsonPath("$.name").value("Court 5"));

        verify(service, times(1)).getCourt(any(CourtDTO.class));
    }

    @Test
    public void testGetCourtByUuid_InvalidUuid() throws Exception {
        String invalidUuid = "b1b44b12-34bc"; // Invalid format

        mockMvc.perform(get(CourtController.BASE_URL + "/get")
                        .param("uuid", invalidUuid)
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest()); // Expecting 400 Bad Request due to validation failure

        verify(service, never()).getCourt(any(CourtDTO.class));
    }

    @Test
    public void testCreateCourt_Success() throws Exception {
        CourtDTO requestDto = createCourtDTO("Court 5", "Dirt");
        requestDto.setGlobalId(null); // ID usually generated by service
        CourtDTO createdDto = createCourtDTO("Court 5", "Dirt");

        when(service.createCourt(any(CourtDTO.class))).thenReturn(createdDto);

        mockMvc.perform(post(CourtController.BASE_URL + "/create")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(requestDto)))
                .andExpect(status().isCreated())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
                .andExpect(jsonPath("$.name").value("Court 5"))
                .andExpect(jsonPath("$.surface").value("Dirt"))
                .andExpect(jsonPath("$.globalId").exists());

        verify(service, times(1)).createCourt(any(CourtDTO.class));
    }

    @Test
    public void testCreateCourt_BadRequest_MissingName() throws Exception {
        // Missing "name" field will trigger @NotNull validation in CourtDTO
        // in combination with CreateCourt group
        String badRequestJson = """
            {"surface": "Dirt"}
        """;

        mockMvc.perform(post(CourtController.BASE_URL + "/create")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(badRequestJson))
                .andExpect(status().isBadRequest());

        verify(service, never()).createCourt(any(CourtDTO.class));
    }

    @Test
    public void testUpdateCourt_Success() throws Exception {
        UUID courtId = UUID.fromString("4930d289-835b-4f60-a326-9bd981389ae6");
        CourtDTO requestDto = createCourtDTO("Court 9", "Gravel");
        requestDto.setGlobalId(courtId);

        when(service.updateCourt(any(CourtDTO.class))).thenReturn(requestDto);

        mockMvc.perform(put(CourtController.BASE_URL + "/update")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(requestDto)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.globalId").value(courtId.toString()))
                .andExpect(jsonPath("$.name").value("Court 9"));

        verify(service, times(1)).updateCourt(any(CourtDTO.class));
    }

    @Test
    public void testUpdateCourt_BadRequest_MissingId() throws Exception {
        // Missing "globalId" in the body
        String badRequestJson = """
            {"name": "Court 2","surface": "Gravel"}
        """;
        // Caught by validation of UpdateCourt.class.

        mockMvc.perform(put(CourtController.BASE_URL + "/update")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(badRequestJson))
                .andExpect(status().isBadRequest());

        verify(service, never()).updateCourt(any(CourtDTO.class));
    }

    @Test
    public void testDeleteCourt_Success() throws Exception {
        UUID courtId = UUID.fromString("4930d289-835b-4f60-a326-9bd981389ae6");

        doNothing().when(service).deleteCourt(any(CourtDTO.class));

        mockMvc.perform(delete(CourtController.BASE_URL + "/delete")
                        .param("uuid", courtId.toString()))
                .andExpect(status().isNoContent()); // Expecting 204 No Content

        verify(service, times(1)).deleteCourt(any(CourtDTO.class));
    }

    @Test
    public void testDeleteCourt_InvalidUuid() throws Exception {
        String invalidUuid = "b1b44b12-34bc";

        mockMvc.perform(delete(CourtController.BASE_URL + "/delete")
                        .param("uuid", invalidUuid))
                .andExpect(status().isBadRequest());

        verify(service, never()).deleteCourt(any(CourtDTO.class));
    }
}
